### ISSUE TITLE
Cannot expand asterisk anymore

### ISSUE THREAD

**Issue by gbrlsnchs** [lincheney/fzf-tab-completion#50] opened 2022-09-02 18:58 UTC
When the plugin is on, pressing tab after asterisk no longer expands to matching files. For example, typing `rm *` and then pressing <kbd>Tab</kbd> doesn't do anything (besides making highlighting being lost).

Then without the plugin it correctly expands to matching files inline.

**Comment by lincheney** [comment] 2022-09-16 04:55
Which shell are you experiencing this on? bash or zsh or both?

**Comment by gbrlsnchs** [comment] 2022-09-19 18:59
ZSH. I haven't tested with Bash.

**Comment by KaXMaXimum** [comment] 2023-03-09 16:48
Same thing happens with bash, I've found out that this is caused by the line
`bind -x '"\t": fzf_bash_completion'`
When this is set, pressing Tab after `**` doesn't expand the standard fzf fuzzy completion properly (doesn't use the custom command we could set using _fzf_compgen_dir for example).

**Comment by lincheney** [comment] 2023-03-15 04:59
the bash case should be fixed by https://github.com/lincheney/fzf-tab-completion/commit/f5788de131f3d03cb3475f085e164ee10f8fc5d5

**Comment by lincheney** [comment] 2023-03-15 05:02
for zsh, I'm not able to replicate
doing `rm *<tab>` opens fzf with many results (1 result for each file + 1 result that has all files + 1 result which is a `*`)

**Comment by lincheney** [comment] 2023-09-01 06:09
> I have the same problem and could reproduce it in a vanilla shell (zsh -dfi) by executing:

Thanks 👍 I can indeed reproduce the issue using this.
I'll have a look to see why this is happening

**Comment by lincheney** [comment] 2023-09-04 00:32
Ok, I think what is happening is that with default zsh, tab is bound to `expand-or-complete`
fzf-tab-completion is able to do the "complete", but it is actually the "expand" that is giving out the results which we are not doing as it is not part of the usual completion mechanism
(to compare, if I also put in `bindkey '^I' menu-complete`, this also does not "expand" `echo *`)
I'll need to see how to emulate this, maybe using the `_expand` completer

**Comment by lincheney** [comment] 2023-09-04 08:41
I've made following changes https://github.com/lincheney/fzf-tab-completion/compare/1ec392c710215cfa45078d2b5b469c6119e89fb0..f0f3facf9f5ae2e1896d88e1988608e67acf49e0
which appear to make the expand work for me
If anyone wants to try it out on their end too

**Comment by f1rstlady** [comment] 2023-09-04 09:14
It works in a default shell but not with my customisations though. In my customised shell, it shows an fzf prompt with the expansion targets as source. Do you have any idea what might cause this behaviour?

**Comment by lincheney** [comment] 2023-09-04 09:27
What do you mean `with the expansion targets as source`?
Something like this?
![Screenshot_2023-09-04_19-21-41](https://github.com/lincheney/fzf-tab-completion/assets/1336117/c4c2e30d-f42b-4400-83c6-cf02e4baaf4c)
Have you turned on the `_expand` completer? It will "expand" globs etc into completion matches for you.
e.g. in my zshrc I have this line: `zstyle ':completion:*' completer _expand _complete _ignored _match _correct _approximate _prefix`

**Comment by f1rstlady** [comment] 2023-09-04 12:15
I mean this (like in your screenshot but without the last two lines):
![20230904-141240](https://github.com/lincheney/fzf-tab-completion/assets/20407973/4bc391dd-6ad9-4806-bdcc-d7f416ad6e87)

No, I haven't enabled the `_expand` completer.

**Comment by lincheney** [comment] 2023-09-05 03:20
ah i think i implemented it in the wrong order, it should expand then complete, but i've made it complete then expand, need to fix it

**Comment by lincheney** [comment] 2023-09-05 08:57
I've pushed https://github.com/lincheney/fzf-tab-completion/commit/1d596ebea90e7fab18892ceb7af013794aad5c4d which I think this should fix it, are you able to test it out?

**Comment by f1rstlady** [comment] 2023-09-05 16:49
Works perfectly :smiley:

**Comment by lincheney** [comment] 2023-09-06 02:53
Awesome, thanks for your help on this one!

**Closed by lincheney** 2023-09-06 02:53 UTC
