### ISSUE TITLE
Good but slow

### ISSUE THREAD

**Issue by zhouzq-thu** [lincheney/fzf-tab-completion#61] opened 2023-01-16 06:18 UTC
I both tried this repo and [fzf-tab](https://github.com/Aloxaf/fzf-tab). I think the search results of this repo is better. However, it is very slow, including the path completion and the command completion. Could you optimize?

**Comment by lincheney** [comment] 2023-01-23 00:20
I've not had issues with performance.
Are you able to provide more details about what exactly is slow?

**Comment by ahmetb** [comment] 2023-05-23 18:43
Came here to say this as well (sorry if this comment is noise).
The speed issue is very obvious if you do `ls `<kbd>Tab</kbd><kbd>Tab</kbd>. It takes a good 200 ms to list files in a dir and put that on fzf.
I know that it's not fzf because if I hit Ctrl+T shortcut (from fzf's own integration with zsh), it's instant.

**Comment by lincheney** [comment] 2023-05-24 00:19
I'm afraid that since I can't reproduce this, I can't fix this myself.

If you are experiencing this issue and you want this to be resolved, you will have to debug why this is happening for you.

Re `probably the fact that it's written in node.js`, you are mistaken; the tab completion for each program is written in the respective language, if you are using the zsh tab completion it is written in zsh. only the tab completion for nodejs is written in nodejs,

**Comment by lincheney** [comment] 2023-06-02 00:25
If you are experiencing slowness on Mac OS, I've merged in https://github.com/lincheney/fzf-tab-completion/pull/73 from @itsjfx which might help. You will need to install GNU grep (instead of using the builtin macos grep).

**Closed** 2023-06-02 06:43 UTC
